package iri

// This file was generated by geniris.

const (
	// Data Quality Vocabulary
	DQV_NS                        = "http://www.w3.org/ns/dqv#"
	DQV_Category                  = DQV_NS + "Category"
	DQV_Dimension                 = DQV_NS + "Dimension"
	DQV_Metric                    = DQV_NS + "Metric"
	DQV_QualityAnnotation         = DQV_NS + "QualityAnnotation"
	DQV_QualityCertificate        = DQV_NS + "QualityCertificate"
	DQV_QualityMeasurement        = DQV_NS + "QualityMeasurement"
	DQV_QualityMeasurementDataset = DQV_NS + "QualityMeasurementDataset"
	DQV_QualityMetadata           = DQV_NS + "QualityMetadata"
	DQV_QualityPolicy             = DQV_NS + "QualityPolicy"
	DQV_UserQualityFeedback       = DQV_NS + "UserQualityFeedback"
	DQV_computedOn                = DQV_NS + "computedOn"
	DQV_expectedDataType          = DQV_NS + "expectedDataType"
	DQV_hasQualityAnnotation      = DQV_NS + "hasQualityAnnotation"
	DQV_hasQualityMeasurement     = DQV_NS + "hasQualityMeasurement"
	DQV_hasQualityMetadata        = DQV_NS + "hasQualityMetadata"
	DQV_inCategory                = DQV_NS + "inCategory"
	DQV_inDimension               = DQV_NS + "inDimension"
	DQV_isMeasurementOf           = DQV_NS + "isMeasurementOf"
	DQV_precision                 = DQV_NS + "precision"
	DQV_qualityAssessment         = DQV_NS + "qualityAssessment"
	DQV_value                     = DQV_NS + "value"
)
