package iri

// This file was generated by geniris.

const (
	// Common Tag vocabulary
	CTAG_NS            = "http://commontag.org/ns#"
	CTAG_AuthorTag     = CTAG_NS + "AuthorTag"
	CTAG_AutoTag       = CTAG_NS + "AutoTag"
	CTAG_ReaderTag     = CTAG_NS + "ReaderTag"
	CTAG_Tag           = CTAG_NS + "Tag"
	CTAG_TaggedContent = CTAG_NS + "TaggedContent"
	CTAG_isAbout       = CTAG_NS + "isAbout"
	CTAG_label         = CTAG_NS + "label"
	CTAG_means         = CTAG_NS + "means"
	CTAG_tagged        = CTAG_NS + "tagged"
	CTAG_taggingDate   = CTAG_NS + "taggingDate"
)
