package iri

// This file was generated by geniris.

const (
	// The W3C Linked Data Platform (LDP) Vocabulary
	LDP_NS                      = "http://www.w3.org/ns/ldp#"
	LDP_Ascending               = LDP_NS + "Ascending"
	LDP_BasicContainer          = LDP_NS + "BasicContainer"
	LDP_Container               = LDP_NS + "Container"
	LDP_Descending              = LDP_NS + "Descending"
	LDP_DirectContainer         = LDP_NS + "DirectContainer"
	LDP_IndirectContainer       = LDP_NS + "IndirectContainer"
	LDP_MemberSubject           = LDP_NS + "MemberSubject"
	LDP_NonRDFSource            = LDP_NS + "NonRDFSource"
	LDP_Page                    = LDP_NS + "Page"
	LDP_PageSortCriterion       = LDP_NS + "PageSortCriterion"
	LDP_PreferContainment       = LDP_NS + "PreferContainment"
	LDP_PreferEmptyContainer    = LDP_NS + "PreferEmptyContainer"
	LDP_PreferMembership        = LDP_NS + "PreferMembership"
	LDP_PreferMinimalContainer  = LDP_NS + "PreferMinimalContainer"
	LDP_RDFSource               = LDP_NS + "RDFSource"
	LDP_Resource                = LDP_NS + "Resource"
	LDP_constrainedBy           = LDP_NS + "constrainedBy"
	LDP_contains                = LDP_NS + "contains"
	LDP_hasMemberRelation       = LDP_NS + "hasMemberRelation"
	LDP_insertedContentRelation = LDP_NS + "insertedContentRelation"
	LDP_isMemberOfRelation      = LDP_NS + "isMemberOfRelation"
	LDP_member                  = LDP_NS + "member"
	LDP_membershipResource      = LDP_NS + "membershipResource"
	LDP_pageSequence            = LDP_NS + "pageSequence"
	LDP_pageSortCollation       = LDP_NS + "pageSortCollation"
	LDP_pageSortCriteria        = LDP_NS + "pageSortCriteria"
	LDP_pageSortOrder           = LDP_NS + "pageSortOrder"
	LDP_pageSortPredicate       = LDP_NS + "pageSortPredicate"
)
