package iri

// This file was generated by geniris.

const (
	// SemWeb Vocab Status ontology
	VS_NS          = "http://www.w3.org/2003/06/sw-vocab-status/ns#"
	VS_moreinfo    = VS_NS + "moreinfo"
	VS_term_status = VS_NS + "term_status"
	VS_userdocs    = VS_NS + "userdocs"
)
