package iri

// This file was generated by geniris.

const (
	// DCMI Type Vocabulary
	DCTYPE_NS                  = "http://purl.org/dc/dcmitype/"
	DCTYPE_Collection          = DCTYPE_NS + "Collection"
	DCTYPE_Dataset             = DCTYPE_NS + "Dataset"
	DCTYPE_Event               = DCTYPE_NS + "Event"
	DCTYPE_Image               = DCTYPE_NS + "Image"
	DCTYPE_InteractiveResource = DCTYPE_NS + "InteractiveResource"
	DCTYPE_MovingImage         = DCTYPE_NS + "MovingImage"
	DCTYPE_PhysicalObject      = DCTYPE_NS + "PhysicalObject"
	DCTYPE_Service             = DCTYPE_NS + "Service"
	DCTYPE_Software            = DCTYPE_NS + "Software"
	DCTYPE_Sound               = DCTYPE_NS + "Sound"
	DCTYPE_StillImage          = DCTYPE_NS + "StillImage"
	DCTYPE_Text                = DCTYPE_NS + "Text"
)
