package iri

// This file was generated by geniris.

const (
	// SDMX-RDF vocabulary
	SDMX_NS                      = "http://purl.org/linked-data/sdmx#"
	SDMX_CodeList                = SDMX_NS + "CodeList"
	SDMX_Concept                 = SDMX_NS + "Concept"
	SDMX_ConceptRole             = SDMX_NS + "ConceptRole"
	SDMX_CountRole               = SDMX_NS + "CountRole"
	SDMX_DataStructureDefinition = SDMX_NS + "DataStructureDefinition"
	SDMX_EntityRole              = SDMX_NS + "EntityRole"
	SDMX_FrequencyRole           = SDMX_NS + "FrequencyRole"
	SDMX_IdentityRole            = SDMX_NS + "IdentityRole"
	SDMX_MeasureTypeRole         = SDMX_NS + "MeasureTypeRole"
	SDMX_NonObsTimeRole          = SDMX_NS + "NonObsTimeRole"
	SDMX_PrimaryMeasureRole      = SDMX_NS + "PrimaryMeasureRole"
	SDMX_TimeRole                = SDMX_NS + "TimeRole"
	SDMX_measureTypeConcept      = SDMX_NS + "measureTypeConcept"
	SDMX_primaryMeasure          = SDMX_NS + "primaryMeasure"
)
