package iri

// This file was generated by geniris.

const (
	LOG_NS                 = "http://www.w3.org/2000/10/swap/log#"
	LOG_Chaff              = LOG_NS + "Chaff"
	LOG_Formula            = LOG_NS + "Formula"
	LOG_List               = LOG_NS + "List"
	LOG_N3Document         = LOG_NS + "N3Document"
	LOG_Other              = LOG_NS + "Other"
	LOG_String             = LOG_NS + "String"
	LOG_Truth              = LOG_NS + "Truth"
	LOG_conclusion         = LOG_NS + "conclusion"
	LOG_conjunction        = LOG_NS + "conjunction"
	LOG_content            = LOG_NS + "content"
	LOG_definitiveDocument = LOG_NS + "definitiveDocument"
	LOG_definitiveService  = LOG_NS + "definitiveService"
	LOG_dtlit              = LOG_NS + "dtlit"
	LOG_equalTo            = LOG_NS + "equalTo"
	LOG_implies            = LOG_NS + "implies"
	LOG_includes           = LOG_NS + "includes"
	LOG_n3String           = LOG_NS + "n3String"
	LOG_notEqualTo         = LOG_NS + "notEqualTo"
	LOG_notIncludes        = LOG_NS + "notIncludes"
	LOG_outputString       = LOG_NS + "outputString"
	LOG_parsedAsN3         = LOG_NS + "parsedAsN3"
	LOG_racine             = LOG_NS + "racine"
	LOG_rawType            = LOG_NS + "rawType"
	LOG_rawUri             = LOG_NS + "rawUri"
	LOG_semantics          = LOG_NS + "semantics"
	LOG_semanticsOrError   = LOG_NS + "semanticsOrError"
	LOG_uri                = LOG_NS + "uri"
)
