package iri

// This file was generated by geniris.

const (
	// The RDF Concepts Vocabulary (RDF)
	RDF_NS           = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	RDF_Alt          = RDF_NS + "Alt"
	RDF_Bag          = RDF_NS + "Bag"
	RDF_HTML         = RDF_NS + "HTML"
	RDF_List         = RDF_NS + "List"
	RDF_PlainLiteral = RDF_NS + "PlainLiteral"
	RDF_Property     = RDF_NS + "Property"
	RDF_Seq          = RDF_NS + "Seq"
	RDF_Statement    = RDF_NS + "Statement"
	RDF_XMLLiteral   = RDF_NS + "XMLLiteral"
	RDF_first        = RDF_NS + "first"
	RDF_langString   = RDF_NS + "langString"
	RDF_nil          = RDF_NS + "nil"
	RDF_object       = RDF_NS + "object"
	RDF_predicate    = RDF_NS + "predicate"
	RDF_rest         = RDF_NS + "rest"
	RDF_subject      = RDF_NS + "subject"
	RDF_type         = RDF_NS + "type"
	RDF_value        = RDF_NS + "value"
)
