package iri

// This file was generated by geniris.

const (
	// Parliament Ontology
	PARL_NS                 = "http://reference.data.gov.uk/def/parliament/"
	PARL_Chamber            = PARL_NS + "Chamber"
	PARL_DevolvedParliament = PARL_NS + "DevolvedParliament"
	PARL_Leader             = PARL_NS + "Leader"
	PARL_Parliament         = PARL_NS + "Parliament"
	PARL_PoliticalParty     = PARL_NS + "PoliticalParty"
	PARL_Post               = PARL_NS + "Post"
	PARL_Seat               = PARL_NS + "Seat"
	PARL_devolvedFrom       = PARL_NS + "devolvedFrom"
	PARL_devolvesTo         = PARL_NS + "devolvesTo"
	PARL_hasMember          = PARL_NS + "hasMember"
	PARL_hasPartyLeader     = PARL_NS + "hasPartyLeader"
	PARL_hasPartyMember     = PARL_NS + "hasPartyMember"
	PARL_holdsLeadership    = PARL_NS + "holdsLeadership"
	PARL_holdsSeat          = PARL_NS + "holdsSeat"
	PARL_leadershipHeldBy   = PARL_NS + "leadershipHeldBy"
	PARL_memberOf           = PARL_NS + "memberOf"
	PARL_partyLeaderOf      = PARL_NS + "partyLeaderOf"
	PARL_partyMemberOf      = PARL_NS + "partyMemberOf"
	PARL_represents         = PARL_NS + "represents"
	PARL_seatHeldBy         = PARL_NS + "seatHeldBy"
)
