package iri

// This file was generated by geniris.

const (
	// RDF Review Vocabulary
	REV_NS            = "http://purl.org/stuff/rev#"
	REV_Comment       = REV_NS + "Comment"
	REV_Feedback      = REV_NS + "Feedback"
	REV_Review        = REV_NS + "Review"
	REV_commenter     = REV_NS + "commenter"
	REV_hasComment    = REV_NS + "hasComment"
	REV_hasFeedback   = REV_NS + "hasFeedback"
	REV_hasReview     = REV_NS + "hasReview"
	REV_maxRating     = REV_NS + "maxRating"
	REV_minRating     = REV_NS + "minRating"
	REV_positiveVotes = REV_NS + "positiveVotes"
	REV_rating        = REV_NS + "rating"
	REV_reviewer      = REV_NS + "reviewer"
	REV_text          = REV_NS + "text"
	REV_title         = REV_NS + "title"
	REV_totalVotes    = REV_NS + "totalVotes"
	REV_type          = REV_NS + "type"
)
