package iri

// This file was generated by geniris.

const (
	// POWDER-S Vocabulary
	WDRS_NS              = "http://www.w3.org/2007/05/powder-s#"
	WDRS_Document        = WDRS_NS + "Document"
	WDRS_Processor       = WDRS_NS + "Processor"
	WDRS_authenticate    = WDRS_NS + "authenticate"
	WDRS_certified       = WDRS_NS + "certified"
	WDRS_certifiedby     = WDRS_NS + "certifiedby"
	WDRS_data_error      = WDRS_NS + "data_error"
	WDRS_describedby     = WDRS_NS + "describedby"
	WDRS_error_code      = WDRS_NS + "error_code"
	WDRS_hasIRI          = WDRS_NS + "hasIRI"
	WDRS_issuedby        = WDRS_NS + "issuedby"
	WDRS_logo            = WDRS_NS + "logo"
	WDRS_matchesregex    = WDRS_NS + "matchesregex"
	WDRS_notknownto      = WDRS_NS + "notknownto"
	WDRS_notmatchesregex = WDRS_NS + "notmatchesregex"
	WDRS_proc_error      = WDRS_NS + "proc_error"
	WDRS_sha1sum         = WDRS_NS + "sha1sum"
	WDRS_supportedby     = WDRS_NS + "supportedby"
	WDRS_tag             = WDRS_NS + "tag"
	WDRS_text            = WDRS_NS + "text"
	WDRS_validfrom       = WDRS_NS + "validfrom"
	WDRS_validuntil      = WDRS_NS + "validuntil"
)
