package iri

// This file was generated by geniris.

const (
	// SKOS XL Vocabulary
	SKOSXL_NS            = "http://www.w3.org/2008/05/skos-xl#"
	SKOSXL_Label         = SKOSXL_NS + "Label"
	SKOSXL_altLabel      = SKOSXL_NS + "altLabel"
	SKOSXL_hiddenLabel   = SKOSXL_NS + "hiddenLabel"
	SKOSXL_labelRelation = SKOSXL_NS + "labelRelation"
	SKOSXL_literalForm   = SKOSXL_NS + "literalForm"
	SKOSXL_prefLabel     = SKOSXL_NS + "prefLabel"
)
