package iri

// This file was generated by geniris.

const (
	// Vocabulary of Interlinked Datasets (VoID)
	VOID_NS                    = "http://rdfs.org/ns/void#"
	VOID_Dataset               = VOID_NS + "Dataset"
	VOID_DatasetDescription    = VOID_NS + "DatasetDescription"
	VOID_Linkset               = VOID_NS + "Linkset"
	VOID_TechnicalFeature      = VOID_NS + "TechnicalFeature"
	VOID_class                 = VOID_NS + "class"
	VOID_classPartition        = VOID_NS + "classPartition"
	VOID_classes               = VOID_NS + "classes"
	VOID_dataDump              = VOID_NS + "dataDump"
	VOID_distinctObjects       = VOID_NS + "distinctObjects"
	VOID_distinctSubjects      = VOID_NS + "distinctSubjects"
	VOID_documents             = VOID_NS + "documents"
	VOID_entities              = VOID_NS + "entities"
	VOID_exampleResource       = VOID_NS + "exampleResource"
	VOID_feature               = VOID_NS + "feature"
	VOID_inDataset             = VOID_NS + "inDataset"
	VOID_linkPredicate         = VOID_NS + "linkPredicate"
	VOID_objectsTarget         = VOID_NS + "objectsTarget"
	VOID_openSearchDescription = VOID_NS + "openSearchDescription"
	VOID_properties            = VOID_NS + "properties"
	VOID_property              = VOID_NS + "property"
	VOID_propertyPartition     = VOID_NS + "propertyPartition"
	VOID_rootResource          = VOID_NS + "rootResource"
	VOID_sparqlEndpoint        = VOID_NS + "sparqlEndpoint"
	VOID_subjectsTarget        = VOID_NS + "subjectsTarget"
	VOID_subset                = VOID_NS + "subset"
	VOID_target                = VOID_NS + "target"
	VOID_triples               = VOID_NS + "triples"
	VOID_uriLookupEndpoint     = VOID_NS + "uriLookupEndpoint"
	VOID_uriRegexPattern       = VOID_NS + "uriRegexPattern"
	VOID_uriSpace              = VOID_NS + "uriSpace"
	VOID_vocabulary            = VOID_NS + "vocabulary"
)
