package iri

// This file was generated by geniris.

const (
	// RDFa Vocabulary for Term and Prefix Assignment, and for Processor Graph Reporting
	RDFA_NS                  = "http://www.w3.org/ns/rdfa#"
	RDFA_DocumentError       = RDFA_NS + "DocumentError"
	RDFA_Error               = RDFA_NS + "Error"
	RDFA_Info                = RDFA_NS + "Info"
	RDFA_PGClass             = RDFA_NS + "PGClass"
	RDFA_Pattern             = RDFA_NS + "Pattern"
	RDFA_PrefixMapping       = RDFA_NS + "PrefixMapping"
	RDFA_PrefixOrTermMapping = RDFA_NS + "PrefixOrTermMapping"
	RDFA_PrefixRedefinition  = RDFA_NS + "PrefixRedefinition"
	RDFA_TermMapping         = RDFA_NS + "TermMapping"
	RDFA_UnresolvedCURIE     = RDFA_NS + "UnresolvedCURIE"
	RDFA_UnresolvedTerm      = RDFA_NS + "UnresolvedTerm"
	RDFA_VocabReferenceError = RDFA_NS + "VocabReferenceError"
	RDFA_Warning             = RDFA_NS + "Warning"
	RDFA_context             = RDFA_NS + "context"
	RDFA_copy                = RDFA_NS + "copy"
	RDFA_prefix              = RDFA_NS + "prefix"
	RDFA_term                = RDFA_NS + "term"
	RDFA_uri                 = RDFA_NS + "uri"
	RDFA_usesVocabulary      = RDFA_NS + "usesVocabulary"
	RDFA_vocabulary          = RDFA_NS + "vocabulary"
)
