package iri

// This file was generated by geniris.

const (
	// Dataset Usage Vocabulary
	DUV_NS             = "http://www.w3.org/ns/duv#"
	DUV_RatingFeedback = DUV_NS + "RatingFeedback"
	DUV_Usage          = DUV_NS + "Usage"
	DUV_UsageTool      = DUV_NS + "UsageTool"
	DUV_UserFeedback   = DUV_NS + "UserFeedback"
	DUV_hasDistributor = DUV_NS + "hasDistributor"
	DUV_hasFeedback    = DUV_NS + "hasFeedback"
	DUV_hasRating      = DUV_NS + "hasRating"
	DUV_hasUsage       = DUV_NS + "hasUsage"
	DUV_hasUsageTool   = DUV_NS + "hasUsageTool"
	DUV_refersTo       = DUV_NS + "refersTo"
)
