package iri

// This file was generated by geniris.

const (
	// The RDF Schema vocabulary (RDFS)
	RDFS_NS                          = "http://www.w3.org/2000/01/rdf-schema#"
	RDFS_Class                       = RDFS_NS + "Class"
	RDFS_Container                   = RDFS_NS + "Container"
	RDFS_ContainerMembershipProperty = RDFS_NS + "ContainerMembershipProperty"
	RDFS_Datatype                    = RDFS_NS + "Datatype"
	RDFS_Literal                     = RDFS_NS + "Literal"
	RDFS_Resource                    = RDFS_NS + "Resource"
	RDFS_comment                     = RDFS_NS + "comment"
	RDFS_domain                      = RDFS_NS + "domain"
	RDFS_isDefinedBy                 = RDFS_NS + "isDefinedBy"
	RDFS_label                       = RDFS_NS + "label"
	RDFS_member                      = RDFS_NS + "member"
	RDFS_range                       = RDFS_NS + "range"
	RDFS_seeAlso                     = RDFS_NS + "seeAlso"
	RDFS_subClassOf                  = RDFS_NS + "subClassOf"
	RDFS_subPropertyOf               = RDFS_NS + "subPropertyOf"
)
