package iri

// This file was generated by geniris.

const (
	// Vocabulary of a Friend
	VOAF_NS                        = "http://purl.org/vocommons/voaf#"
	VOAF_DatasetOccurrences        = VOAF_NS + "DatasetOccurrences"
	VOAF_Vocabulary                = VOAF_NS + "Vocabulary"
	VOAF_VocabularySpace           = VOAF_NS + "VocabularySpace"
	VOAF_classNumber               = VOAF_NS + "classNumber"
	VOAF_dataset                   = VOAF_NS + "dataset"
	VOAF_exampleDataset            = VOAF_NS + "exampleDataset"
	VOAF_extends                   = VOAF_NS + "extends"
	VOAF_generalizes               = VOAF_NS + "generalizes"
	VOAF_hasDisjunctionsWith       = VOAF_NS + "hasDisjunctionsWith"
	VOAF_hasEquivalencesWith       = VOAF_NS + "hasEquivalencesWith"
	VOAF_inDataset                 = VOAF_NS + "inDataset"
	VOAF_metadataVoc               = VOAF_NS + "metadataVoc"
	VOAF_occurrences               = VOAF_NS + "occurrences"
	VOAF_occurrencesInDatasets     = VOAF_NS + "occurrencesInDatasets"
	VOAF_occurrencesInVocabularies = VOAF_NS + "occurrencesInVocabularies"
	VOAF_propertyNumber            = VOAF_NS + "propertyNumber"
	VOAF_reliesOn                  = VOAF_NS + "reliesOn"
	VOAF_reusedByDatasets          = VOAF_NS + "reusedByDatasets"
	VOAF_reusedByVocabularies      = VOAF_NS + "reusedByVocabularies"
	VOAF_similar                   = VOAF_NS + "similar"
	VOAF_specializes               = VOAF_NS + "specializes"
	VOAF_toDoList                  = VOAF_NS + "toDoList"
	VOAF_usageInDataset            = VOAF_NS + "usageInDataset"
	VOAF_usedBy                    = VOAF_NS + "usedBy"
)
