package iri

// This file was generated by geniris.

const (
	GRDDL_NS                      = "http://www.w3.org/2003/g/data-view#"
	GRDDL_InformationResource     = GRDDL_NS + "InformationResource"
	GRDDL_RDFGraph                = GRDDL_NS + "RDFGraph"
	GRDDL_RootNode                = GRDDL_NS + "RootNode"
	GRDDL_Transformation          = GRDDL_NS + "Transformation"
	GRDDL_TransformationProperty  = GRDDL_NS + "TransformationProperty"
	GRDDL_danc                    = GRDDL_NS + "danc"
	GRDDL_grddl_wg                = GRDDL_NS + "grddl-wg"
	GRDDL_grddlProject            = GRDDL_NS + "grddlProject"
	GRDDL_namespaceTransformation = GRDDL_NS + "namespaceTransformation"
	GRDDL_profileTransformation   = GRDDL_NS + "profileTransformation"
	GRDDL_result                  = GRDDL_NS + "result"
	GRDDL_transformation          = GRDDL_NS + "transformation"
	GRDDL_transformationProperty  = GRDDL_NS + "transformationProperty"
)
