package iri

// This file was generated by geniris.

const (
	// The data catalog vocabulary
	DCAT_NS             = "http://www.w3.org/ns/dcat#"
	DCAT_Catalog        = DCAT_NS + "Catalog"
	DCAT_CatalogRecord  = DCAT_NS + "CatalogRecord"
	DCAT_Dataset        = DCAT_NS + "Dataset"
	DCAT_Distribution   = DCAT_NS + "Distribution"
	DCAT_Download       = DCAT_NS + "Download"
	DCAT_Feed           = DCAT_NS + "Feed"
	DCAT_WebService     = DCAT_NS + "WebService"
	DCAT_accessURL      = DCAT_NS + "accessURL"
	DCAT_byteSize       = DCAT_NS + "byteSize"
	DCAT_bytes          = DCAT_NS + "bytes"
	DCAT_contactPoint   = DCAT_NS + "contactPoint"
	DCAT_dataDictionary = DCAT_NS + "dataDictionary"
	DCAT_dataQuality    = DCAT_NS + "dataQuality"
	DCAT_dataset        = DCAT_NS + "dataset"
	DCAT_distribution   = DCAT_NS + "distribution"
	DCAT_downloadURL    = DCAT_NS + "downloadURL"
	DCAT_granularity    = DCAT_NS + "granularity"
	DCAT_keyword        = DCAT_NS + "keyword"
	DCAT_landingPage    = DCAT_NS + "landingPage"
	DCAT_mediaType      = DCAT_NS + "mediaType"
	DCAT_record         = DCAT_NS + "record"
	DCAT_size           = DCAT_NS + "size"
	DCAT_theme          = DCAT_NS + "theme"
	DCAT_themeTaxonomy  = DCAT_NS + "themeTaxonomy"
)
