package iri

// This file was generated by geniris.

const (
	// The Statistical Core Vocabulary (SCOVO)
	SCOVO_NS        = "http://purl.org/NET/scovo#"
	SCOVO_Dataset   = SCOVO_NS + "Dataset"
	SCOVO_Dimension = SCOVO_NS + "Dimension"
	SCOVO_Item      = SCOVO_NS + "Item"
	SCOVO_dataset   = SCOVO_NS + "dataset"
	SCOVO_datasetOf = SCOVO_NS + "datasetOf"
	SCOVO_dimension = SCOVO_NS + "dimension"
	SCOVO_max       = SCOVO_NS + "max"
	SCOVO_min       = SCOVO_NS + "min"
)
