package iri

// This file was generated by geniris.

const (
	// Metadata terms related to the DCMI Abstract Model
	DCAM_NS                       = "http://purl.org/dc/dcam/"
	DCAM_VocabularyEncodingScheme = DCAM_NS + "VocabularyEncodingScheme"
	DCAM_memberOf                 = DCAM_NS + "memberOf"
)
