package iri

// This file was generated by geniris.

const (
	// Web Of Trust vocabulary
	WOT_NS                = "http://xmlns.com/wot/0.1/"
	WOT_EncryptedDocument = WOT_NS + "EncryptedDocument"
	WOT_Endorsement       = WOT_NS + "Endorsement"
	WOT_PubKey            = WOT_NS + "PubKey"
	WOT_SigEvent          = WOT_NS + "SigEvent"
	WOT_User              = WOT_NS + "User"
	WOT_assurance         = WOT_NS + "assurance"
	WOT_encryptedTo       = WOT_NS + "encryptedTo"
	WOT_encrypter         = WOT_NS + "encrypter"
	WOT_fingerprint       = WOT_NS + "fingerprint"
	WOT_hasKey            = WOT_NS + "hasKey"
	WOT_hex_id            = WOT_NS + "hex_id"
	WOT_identity          = WOT_NS + "identity"
	WOT_length            = WOT_NS + "length"
	WOT_pubkeyAddress     = WOT_NS + "pubkeyAddress"
	WOT_sigdate           = WOT_NS + "sigdate"
	WOT_signed            = WOT_NS + "signed"
	WOT_signer            = WOT_NS + "signer"
	WOT_sigtime           = WOT_NS + "sigtime"
)
