package iri

// This file was generated by geniris.

const (
	// The Event ontology
	EVENT_NS               = "http://purl.org/NET/c4dm/event.owl#"
	EVENT_Event            = EVENT_NS + "Event"
	EVENT_Factor           = EVENT_NS + "Factor"
	EVENT_Product          = EVENT_NS + "Product"
	EVENT_agent            = EVENT_NS + "agent"
	EVENT_agent_in         = EVENT_NS + "agent_in"
	EVENT_factor           = EVENT_NS + "factor"
	EVENT_factor_of        = EVENT_NS + "factor_of"
	EVENT_hasAgent         = EVENT_NS + "hasAgent"
	EVENT_hasFactor        = EVENT_NS + "hasFactor"
	EVENT_hasLiteralFactor = EVENT_NS + "hasLiteralFactor"
	EVENT_hasProduct       = EVENT_NS + "hasProduct"
	EVENT_hasSubEvent      = EVENT_NS + "hasSubEvent"
	EVENT_isAgentIn        = EVENT_NS + "isAgentIn"
	EVENT_isFactorOf       = EVENT_NS + "isFactorOf"
	EVENT_literal_factor   = EVENT_NS + "literal_factor"
	EVENT_place            = EVENT_NS + "place"
	EVENT_producedIn       = EVENT_NS + "producedIn"
	EVENT_produced_in      = EVENT_NS + "produced_in"
	EVENT_product          = EVENT_NS + "product"
	EVENT_sub_event        = EVENT_NS + "sub_event"
	EVENT_time             = EVENT_NS + "time"
)
