package iri

// This file was generated by geniris.

const (
	// Dublin Core Metadata Element Set, Version 1.1
	DCE_NS          = "http://purl.org/dc/elements/1.1/"
	DCE_contributor = DCE_NS + "contributor"
	DCE_coverage    = DCE_NS + "coverage"
	DCE_creator     = DCE_NS + "creator"
	DCE_date        = DCE_NS + "date"
	DCE_description = DCE_NS + "description"
	DCE_format      = DCE_NS + "format"
	DCE_identifier  = DCE_NS + "identifier"
	DCE_language    = DCE_NS + "language"
	DCE_publisher   = DCE_NS + "publisher"
	DCE_relation    = DCE_NS + "relation"
	DCE_rights      = DCE_NS + "rights"
	DCE_source      = DCE_NS + "source"
	DCE_subject     = DCE_NS + "subject"
	DCE_title       = DCE_NS + "title"
	DCE_type        = DCE_NS + "type"
)
