package iri

// This file was generated by geniris.

const (
	// VANN: A vocabulary for annotating vocabulary descriptions
	VANN_NS                       = "http://purl.org/vocab/vann/"
	VANN_changes                  = VANN_NS + "changes"
	VANN_example                  = VANN_NS + "example"
	VANN_preferredNamespacePrefix = VANN_NS + "preferredNamespacePrefix"
	VANN_preferredNamespaceUri    = VANN_NS + "preferredNamespaceUri"
	VANN_termGroup                = VANN_NS + "termGroup"
	VANN_usageNote                = VANN_NS + "usageNote"
)
