package iri

// This file was generated by geniris.

const (
	// WGS84 Geo Positioning: an RDF vocabulary
	GEO_NS           = "http://www.w3.org/2003/01/geo/wgs84_pos#"
	GEO_Point        = GEO_NS + "Point"
	GEO_SpatialThing = GEO_NS + "SpatialThing"
	GEO_alt          = GEO_NS + "alt"
	GEO_lat          = GEO_NS + "lat"
	GEO_lat_long     = GEO_NS + "lat_long"
	GEO_location     = GEO_NS + "location"
	GEO_long         = GEO_NS + "long"
)
