package iri

// This file was generated by geniris.

const (
	// Asset Description Metadata Schema (ADMS)
	ADMS_NS                      = "http://www.w3.org/ns/adms#"
	ADMS_Asset                   = ADMS_NS + "Asset"
	ADMS_AssetDistribution       = ADMS_NS + "AssetDistribution"
	ADMS_AssetRepository         = ADMS_NS + "AssetRepository"
	ADMS_Identifier              = ADMS_NS + "Identifier"
	ADMS_identifier              = ADMS_NS + "identifier"
	ADMS_includedAsset           = ADMS_NS + "includedAsset"
	ADMS_interoperabilityLevel   = ADMS_NS + "interoperabilityLevel"
	ADMS_last                    = ADMS_NS + "last"
	ADMS_next                    = ADMS_NS + "next"
	ADMS_prev                    = ADMS_NS + "prev"
	ADMS_representationTechnique = ADMS_NS + "representationTechnique"
	ADMS_sample                  = ADMS_NS + "sample"
	ADMS_schemeAgency            = ADMS_NS + "schemeAgency"
	ADMS_status                  = ADMS_NS + "status"
	ADMS_supportedSchema         = ADMS_NS + "supportedSchema"
	ADMS_translation             = ADMS_NS + "translation"
	ADMS_versionNotes            = ADMS_NS + "versionNotes"
)
