package iri

const (
	// PRISM Namespace
	PRISM_NS                 = "http://prismstandard.org/namespaces/1.2/basic/"
	PRISM_byteCount          = PRISM_NS + "byteCount"
	PRISM_category           = PRISM_NS + "category"
	PRISM_complianceProfile  = PRISM_NS + "complianceProfile"
	PRISM_copyright          = PRISM_NS + "copyright"
	PRISM_corporateEntity    = PRISM_NS + "corporateEntity"
	PRISM_coverDate          = PRISM_NS + "coverDate"
	PRISM_coverDisplayDate   = PRISM_NS + "coverDisplayDate"
	PRISM_creationDate       = PRISM_NS + "creationDate"
	PRISM_distributor        = PRISM_NS + "distributor"
	PRISM_edition            = PRISM_NS + "edition"
	PRISM_eIssn              = PRISM_NS + "eIssn"
	PRISM_embargoDate        = PRISM_NS + "embargoDate"
	PRISM_endingPage         = PRISM_NS + "endingPage"
	PRISM_event              = PRISM_NS + "event"
	PRISM_expirationDate     = PRISM_NS + "expirationDate"
	PRISM_hasAlternative     = PRISM_NS + "hasAlternative"
	PRISM_hasCorrection      = PRISM_NS + "hasCorrection"
	PRISM_hasFormat          = PRISM_NS + "hasFormat"
	PRISM_hasPart            = PRISM_NS + "hasPart"
	PRISM_hasPreviousVersion = PRISM_NS + "hasPreviousVersion"
	PRISM_hasTranslation     = PRISM_NS + "hasTranslation"
	PRISM_industry           = PRISM_NS + "industry"
	PRISM_isCorrectionOf     = PRISM_NS + "isCorrectionOf"
	PRISM_isFormatOf         = PRISM_NS + "isFormatOf"
	PRISM_isPartOf           = PRISM_NS + "isPartOf"
	PRISM_isReferencedBy     = PRISM_NS + "isReferencedBy"
	PRISM_isRequiredBy       = PRISM_NS + "isRequiredBy"
	PRISM_issn               = PRISM_NS + "issn"
	PRISM_issueIdentifier    = PRISM_NS + "issueIdentifier"
	PRISM_issueName          = PRISM_NS + "issueName"
	PRISM_isTranslationOf    = PRISM_NS + "isTranslationOf"
	PRISM_isVersionOf        = PRISM_NS + "isVersionOf"
	PRISM_location           = PRISM_NS + "location"
	PRISM_modificationDate   = PRISM_NS + "modificationDate"
	PRISM_number             = PRISM_NS + "number"
	PRISM_objectTitle        = PRISM_NS + "objectTitle"
	PRISM_organization       = PRISM_NS + "organization"
	PRISM_person             = PRISM_NS + "person"
	PRISM_publicationDate    = PRISM_NS + "publicationDate"
	PRISM_publicationName    = PRISM_NS + "publicationName"
	PRISM_receptionDate      = PRISM_NS + "receptionDate"
	PRISM_references         = PRISM_NS + "references"
	PRISM_requires           = PRISM_NS + "requires"
	PRISM_rightsAgent        = PRISM_NS + "rightsAgent"
	PRISM_section            = PRISM_NS + "section"
	PRISM_startingPage       = PRISM_NS + "startingPage"
	PRISM_subsection1        = PRISM_NS + "subsection1"
	PRISM_subsection2        = PRISM_NS + "subsection2"
	PRISM_teaser             = PRISM_NS + "teaser"
	PRISM_volume             = PRISM_NS + "volume"
	PRISM_wordCount          = PRISM_NS + "wordCount"
	// PRISM Rights Language
	PRL_NS        = "http://prismstandard.org/namespaces/prl/1.2/"
	PRL_geography = PRL_NS + "geography"
	PRL_industry  = PRL_NS + "industry"
	PRL_usage     = PRL_NS + "usage"
	// PRISM Inline Markup Namespace
	PIM_NS           = "http://prismstandard.org/namespaces/1.2/pim/"
	PIM_event        = PIM_NS + "event"
	PIM_industry     = PIM_NS + "industry"
	PIM_location     = PIM_NS + "location"
	PIM_objectTitle  = PIM_NS + "objectTitle"
	PIM_organization = PIM_NS + "organization"
	PIM_person       = PIM_NS + "person"
	PIM_quote        = PIM_NS + "quote"
	// PRISM Controlled Vocabulary Namespace
	PCV_NS           = "http://prismstandard.org/namespaces/1.2/pcv/"
	PCV_broaderTerm  = PCV_NS + "broaderTerm"
	PCV_code         = PCV_NS + "code"
	PCV_definition   = PCV_NS + "definition"
	PCV_Descriptor   = PCV_NS + "Descriptor"
	PCV_label        = PCV_NS + "label"
	PCV_narrowerTerm = PCV_NS + "narrowerTerm"
	PCV_relatedTerm  = PCV_NS + "relatedTerm"
	PCV_synonym      = PCV_NS + "synonym"
	PCV_vocabulary   = PCV_NS + "vocabulary"
)
